version: 0.0
os: linux
files:
  - source: /Gemfile
    destination: /opt/ruby-app
  - source: /Gemfile.lock
    destination: /opt/ruby-app
  - source: /public
    destination: /opt/ruby-app/public
  - source: /views
    destination: /opt/ruby-app/views
  - source: /web.rb
    destination: /opt/ruby-app 
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/setup_app
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
